Shadow/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'project'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    
    path('', include('blog.urls')),
    path('after-login/', include('users.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('', include('api.urls')),
    path(r'captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path, include, re_path
from . import views
from .views import *
from rest_framework import routers


# router = routers.DefaultRouter()
#p = re_path(r'^posts/(?P<city>\w+)/$', views.post_list, name='city'),
#p = url('^posts/(?P<city>.+)/$', post_list.as_view())
#router.register('posts/<city>/', views.post_list)
# router.register(p)
# router.register('cameras', views.camera_list)

router = routers.DefaultRouter()
#router.register('postings', views.post_list1)
#router.register('cameras', views.camera_list1)
#router.register('authority', views.authority_list)
#router.register('journalist', views.journalist_list)
urlpatterns = [
    # path('api1', views.api, name='api'),
    # path('rest/cameras/', views.camera_list, name='camera_list'),
    path("rest/post/<str:city>", views.post_list.as_view(), name="results_api"),
    path("rest/posts/", views.post_list1.as_view(), name="results_api"),
    path("rest/cameras/", views.camera_list1.as_view(), name="results_api"),
    path("rest/authority/", views.authority_list.as_view(), name="results_api"),
    path("rest/journalist/", views.journalist_list.as_view(), name="results_api"),

    path("rest/camera/<str:city>",
         views.camera_list.as_view(), name="results_api"),
    #path('rest/', include(router.urls)),

    # path('rest/', include(router.urls)),

]

blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing-page'),
    path('blog/home/', PostListView, name='blog-home'),
    path('blog/home/<int:check>/', views.PostListView_Auth, name='blog-home-authority'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('registerCamera/', views.RegisterCamera, name='register-camera'),
    path('post/<int:pk>/comment/', views.add_comment_to_post,
         name='add_comment_to_post'),
    
    path('posttt/<int:pk>/approve/',
         views.post_approve, name='post_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('like/', views.upvote_post, name='upvote_post'),

    ######################################################################################################################################################
    #EDIT STARTS#
    ######################################################################################################################################################

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('invalid/', views.invalid, name='invalid_page'),

    ######################################################################################################################################################
    #EDIT STOPS#
    ######################################################################################################################################################


    path('dislike/', views.downvote_post, name='downvote_post'),
    path('graphs/', views.linkgraph, name='linkgraph'),
    path('graphs/india', views.indianmap, name='indianmap'),
    path('graphs/line', views.linegraph, name='linegraph'),
    path('graphs/pie', views.piechart, name="piechart"),
    path('graphs/donut', views.donut, name="donut"),
    path('cameralist/', views.cameraslist, name='cameraslist'),
    path('api', views.post_rest.as_view(), name='api'),
    path('trending/', views.post_ordered_by_upvotes, name='trend'),
    path('trending/monthly', views.post_ordered_by_upvotes_monthly, name='monthly-trend'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MinLengthValidator, MaxLengthValidator

# Create your models here.


class State(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Location(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True)

class Post(models.Model):
    CRIMETYPE_CHOICES = (('White-Collar Crime', 'White-Collar Crime'), ('Robbery', 'Robbery'), ('Rape', 'Rape'), ('Assualt', 'Assault'), ('Arson', 'Arson'), ('Homicide', 'Homicide'), ('Crimes Against Morality', 'Crimes Against Morality'), ('Illegal goods', 'Illegal goods'),
                         ('Poaching and Illegal Felling', 'Poaching and Illegal Felling'), ('Adultery in Food Sector', 'Adultery in Food Sector'), ('Ill-treatment of Workers', 'Ill-treatment of Workers'), ('Tax Evasion', 'Tax Evasion'), ('Sexual Harrassment', 'Sexual Harrassment'), ('Communal Crimes', 'Communal Crimes'))
    #STATE_CHOICES = (("Select State","Select State"),("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),("Goa","Goa"),("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),("Jammu and Kashmir ","Jammu and Kashmir "),("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),("Sikkim","Sikkim"),("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),("West Bengal","West Bengal"),("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),("Lakshadweep","Lakshadweep"),("National Capital Territory of Delhi","National Capital Territory of Delhi"),("Puducherry","Puducherry"))
    CRIMETYPE1_CHOICES = (('None', 'None'), ('White-Collar Crime', 'White-Collar Crime'), ('Robbery', 'Robbery'), ('Rape', 'Rape'), ('Assualt', 'Assault'), ('Arson', 'Arson'), ('Homicide', 'Homicide'), ('Crimes Against Morality', 'Crimes Against Morality'), ('Illegal goods', 'Illegal goods'),
                          ('Poaching and Illegal Felling', 'Poaching and Illegal Felling'), ('Adultery in Food Sector', 'Adultery in Food Sector'), ('Ill-treatment of Workers', 'Ill-treatment of Workers'), ('Tax Evasion', 'Tax Evasion'), ('Sexual Harrassment', 'Sexual Harrassment'), ('Communal Crimes', 'Communal Crimes'))

    AUTHORITYTYPES_CHOICES = (('Department of Consumer Affairs', 'Department of Consumer Affairs'), ('Department of Food and Public Distribution', 'Department of Food and Public Distribution'), ('Serious Fraud Investigation Office', 'Serious Fraud Investigation Office'), ('Forest Reserve Conservation Authority', 'Forest Reserve Conservation Authority'),
                              ('Criminal Investigation Department', 'Criminal Investigation Department'), ('Labour Bureau', 'Labour Bureau'), ('National Commission for Minorities', 'National Commission for Minorities'), ('National Commission for Women', 'National Commission for Women'), ('Income Tax Department', 'Income Tax Department'))

    title = models.CharField(max_length=100)
    crimetype1 = models.CharField(
        max_length=100, default='not provided', choices=CRIMETYPE_CHOICES, null=True)
    crimetype2 = models.CharField(
        max_length=100, default=None, choices=CRIMETYPE1_CHOICES, null=True)
    crimetype3 = models.CharField(
        max_length=100, default=None, choices=CRIMETYPE1_CHOICES, null=True)
    crimetype4 = models.CharField(
        max_length=100, default=None, choices=CRIMETYPE1_CHOICES, null=True)
    authority = models.CharField(
        max_length=10000, default='Incometax Department')
    location = models.TextField(max_length=60)
    content = models.TextField(max_length=300)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=20, default="India")
    upvotes = models.ManyToManyField(User, related_name='upvotes', blank=True)
    downvotes = models.ManyToManyField(
        User, related_name='downvotes', blank=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    tags = models.CharField(max_length=1000,default="None")

    #state = models.CharField(max_length=100, default='not provided', choices = STATE_CHOICES)
    #city = models.CharField(max_length=20, default='not provided')
    # city = models.ForeignKey(City, default='Delhi',
    #                          on_delete=models.CASCADE, null=False)
    pincode = models.CharField('Pincode', validators=[
                               MinLengthValidator(6)], max_length=6, default='000000')
    photo1 = models.ImageField(upload_to='post_pics',
                               blank='True')
    photo2 = models.ImageField(upload_to='post_pics',
                               blank='True')
    photo3 = models.ImageField(upload_to='post_pics',
                               blank='True')
    photo4 = models.ImageField(upload_to='post_pics',
                               blank='True')

    def __str__(self):
        return self.title

    def total_upvotes(self):
        return self.upvotes.count()

    def total_downvotes(self):
        return self.downvotes.count()

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk": self.pk})

    def approve(self):
        self.approved_posts = True
        self.save()

    def approved_posts1(self):
        return self.post.filter(approved_posts=True)

class Comment(models.Model):
    post = models.ForeignKey(
        'blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    class Meta:
        ordering = ["-created_date"]


class registerCamera(models.Model):
    STATE_CHOICES = (("Select State","Select State"),("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),("Goa","Goa"),("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),("Jammu and Kashmir ","Jammu and Kashmir "),("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),("Sikkim","Sikkim"),("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),("West Bengal","West Bengal"),("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),("Lakshadweep","Lakshadweep"),("National Capital Territory of Delhi","National Capital Territory of Delhi"),("Puducherry","Puducherry"))

    
    address = models.CharField(max_length=60)
    pincode = models.CharField('Pincode', validators=[
                               MinLengthValidator(6)], max_length=6)
    state = models.CharField(max_length=100, default='not provided', choices = STATE_CHOICES)
    city = models.CharField(max_length=20)

    def __str__(self):
        return self.address

blog/forms.py
from django import forms
from .models import Post, Comment, registerCamera, City, State, Location
CRIMETYPE_CHOICES = (('All', 'All'), ('White-Collar Crime', 'White-Collar Crime'), ('Robbery', 'Robbery'), ('Rape', 'Rape'), ('Assualt', 'Assault'), ('Arson', 'Arson'), ('Homicide', 'Homicide'), ('Crimes Against Morality', 'Crimes Against Morality'), ('Illegal goods', 'Illegal goods'),
                     ('Poaching and Illegal Felling', 'Poaching and Illegal Felling'), ('Adultery in Food Sector', 'Adultery in Food Sector'), ('Ill-treatment of Workers', 'Ill-treatment of Workers'), ('Tax Evasion', 'Tax Evasion'), ('Sexual Harrassment', 'Sexual Harrassment'), ('Communal Crimes', 'Communal Crimes'))


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)


class CameraForm(forms.ModelForm):

    class Meta:
        model = registerCamera
        fields = {'address', 'pincode', 'state', 'city'}

######################################################################################################################################################
                                                                #EDIT STARTS#
######################################################################################################################################################


class BlogForm(forms.ModelForm):
    pincode = forms.CharField(widget=forms.TextInput
                              (attrs={'placeholder': 'Enter Six-Digit Pincode'}))

    class Meta:
        model = Post
        fields = ('title', 'location', 'pincode', 'state', 'city',
                  'content', 'crimetype1', 'crimetype2', 'crimetype3', 'crimetype4', 'photo1', 'photo2', 'photo3', 'photo4')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(
                    state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.state.city_set.order_by(
                'name')



# class SortCityForm(form.Form):
#     citylist = getCity()
#     cityname = forms.ChoiceField(citylist)
    

class SortCrimeType(forms.Form):
    crimetype = forms.ChoiceField(choices=CRIMETYPE_CHOICES)

# class Checkbox(forms.Form):
#     give_All = forms.BooleanField()

#     def __init__(self):
#         if check_something():
#             self.fields['give_All'].initial  = False
    

class SortLocation(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SortLocation, self).__init__(*args, **kwargs)
        self.fields['state'].required = False
        self.fields['city'].required = False


    class Meta:
        model = Location
        fields = ('state','city')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(
                    state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.state.city_set.order_by(
                'name')


######################################################################################################################################################
                                                                #EDIT STOPS#
######################################################################################################################################################

blog/templates/blog/add_comment_to_post.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<!-- Basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Site Metas -->
<title>S.H.A.D.O.W - Forum</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">

<!-- Site Icons -->
<link rel="shortcut icon" href="{% static "images/favicon2.ico" %}" type="image/x-icon" />
<link rel="apple-touch-icon" href="{% static "images/apple-touch-icon2.png" %}">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<!-- Site CSS -->
<link rel="stylesheet" href="{% static "style.css" %}">
<!-- Responsive CSS -->
<link rel="stylesheet" href="{% static "css/responsive.css" %}">
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static "css/custom.css" %}">
<script src="{% static "js/modernizr.js" %}"></script> <!-- Modernizr -->

<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
    #mainNav {
        opacity: 70%;
        transition: opacity 1s;
    }

    #mainNav:hover {
        opacity: 100%;
    }

    body {
        background-image: url({% static "uploads/BG.jpg" %});
        background-repeat: repeat-y;
    }
</style>
</head>

<body id="page-top" class="politics_version">
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="background-color: #242222">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <img class="img-fluid" src="{% static "images/test.png" %}" alt="" />
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog-home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post-create' %}">Add Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register-camera' %}">Camera</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    <div class="container" style="margin:10em;padding:5em; background-color: white;">
        <h1>New comment</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="save btn btn-default">Comment</button>
        </form>
    </div>
    {% endblock %}
</body>

</html>

blog/templates/blog/home1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Site Metas -->
<title>S.H.A.D.O.W - Forum</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">

<!-- Site Icons -->
<link rel="shortcut icon" href="{% static "images/favicon2.ico" %}" type="image/x-icon" />
<link rel="apple-touch-icon" href="{% static "images/apple-touch-icon2.png" %}">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<!-- Site CSS -->
<link rel="stylesheet" href="{% static "style.css" %}">
<!-- Responsive CSS -->
<link rel="stylesheet" href="{% static "css/responsive.css" %}">
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static "css/custom.css" %}">
<script src="{% static "js/modernizr.js" %}"></script> <!-- Modernizr -->

<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
	#mainNav {
		opacity: 70%;
		transition: opacity 1s;
	}

	#mainNav:hover {
		opacity: 100%;
	}

	.bg {
		position: absolute;
		width: 100%;
		background-position: center;
		background-repeat: repeat-y;
		z-index: -100;
	}

	body {
		background-image: url({% static "uploads/BG.jpg" %});
		background-repeat: repeat-y;
	}
</style>
</head>

<body id="page-top" class="politics_version">
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="background-color: #242222">
			<div class="container">
				<a class="navbar-brand js-scroll-trigger" href="#page-top">
					<img class="img-fluid" src="{% static "images/test.png" %}" alt="" />
				</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
					data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
					aria-label="Toggle navigation">
					Menu
					<i class="fa fa-bars"></i>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
					<ul class="navbar-nav text-uppercase ml-auto">
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'landing-page' %}">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'profile' %}">Profile</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'post-create' %}">Add Post</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'register-camera' %}">Camera</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'cameraslist' %}">Camera List</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'logout' %}">Logout</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'login' %}">Login</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'register' %}">Register</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
		{% block content %}
		<img>
		<div class="container" style="width:100%; margin-top:10em">
			{% if request.user.is_authenticated %}
			{% for post in posts %}
			<div class="media border p-5" style="background-color: white;">
				<article class="media content-section">
					<div class="media-body">
						<div class="article-metadata">Posted by
							{% if request.user == post.author%}
								<a class="mr-2" href="{% url 'profile'%}"> {{ post.author }}</a>

							{% else %}
								<a class="mr-2" href="{% url 'userprofile' post.id%}"> {{ post.author }}</a>
							{% endif %}
							<small class="text-muted"> on {{ post.date_posted|date:"F d, Y"}}</small>
						</div>
						<h2><a class="article-title" href="{% url 'post-detail' post.id %}"> {{ post.title }}</a></h2>
						<p class="text-muted">Incident reported in {{ post.city }} STATE : {{ post.state }}</p><br>
						<p class="article-content">{{ post.content }}</p>
						<p>{{ post.text|linebreaksbr }}</p>
						{% if request.user.is_authenticated %}
						<form action="{% url 'upvote_post' %}" method="post">
							{% csrf_token %}
							{% if is_upvoted %}
							<button type="submit" id="upvote" name="post_id" value="{{ post.id }}"
								class="btn btn-primary btn-success mr-md-0">Upvoted!</button>
							{% else %}
							<!-- <button type="submit" id="upvote" name="post_id" value="{{ post.id }}"
							class="btn btn-primary mr-md-0"><i class="fa fa-arrow-up">&nbsp;</i>Upvote</button> -->
							{% endif %}
						</form>
						{% endif %}
						<span style="float:left">{{post.total_upvotes}} Upvotes{{ total_upvotes|pluralize }}</span>

						{% if request.user.is_authenticated %}
						<form action="{% url 'downvote_post' %}" method="post" style="float: left;">
							{% csrf_token %}
							{% if is_downvoted %}
							<button type="submit" id="downvote" name="post_id" value="{{ post.id }}"
								class="btn btn-primary btn-success mr-md-0">Downvoted!</button>
							{% else %}
							<!-- <button type="submit" id="downvote" name="post_id" value="{{ post.id }}"
							class="btn btn-primary mr-md-0">Downvote</button> -->
							{% endif %}

						</form>
						{% endif %}
						<span style="float:left;margin-left: 15px;">{{post.total_downvotes}}
							Downvotes{{ total_downvotes|pluralize }}</span>



						<a href="{% url 'post-detail' pk=post.pk %}">&nbsp;Comments: {{ post.comments.count }}</a>
						<br><br>
					</div>
				</article>
			</div>
			{% endfor %}
			{% endif %}
			{% load crispy_forms_tags %}
			<div class="container" style="padding:5em;margin:10em;background-color: white;">
				<div class="content-section" style="margin-top:1em;">
					<form method="POST" enctype="multipart/form-data" id="personForm"
						data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
						{% csrf_token %}
						<fieldset class="form-group">
							<legend class="border-bottom mb-4"> Sort Posts </legend>
							{{ form1 | crispy }}
							{{ form2 | crispy }}
						</fieldset>
						<div class="form-group">
							<button class="btn btn-outline-info" type="submit"> Search </button>
						</div>
					</form>
				</div>
			</div>

			<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
			<script>
				$("#id_state").change(function () {
					var url = $("#personForm").attr("data-cities-url");
					var stateId = $(this).val();

					$.ajax({
						url: url,
						data: {
							'state': stateId
						},
						success: function (data) {
							$("#id_city").html(data);
						}
					});

				});
			</script>
			{% endblock content %}
		</div>
</body>

</html>